Full project implementation for JS best practices assesment
rskinnerc/to-do-list-review pull request #1
Opened 2022-05-02 19:15 UTC by rskinnerc

#### In this PR I have implemented all the project's requirements. This PR is intended to be used as part of JS best practices assessment exercise.

#### In this PR I have:
- Completed the full project requirements
- Added CRUD Operation s to the todo list
- Added localStorage logic
- Added deployment targets in webpack config.
- Fixed linter errors

2022-05-02 21:03 UTC, wandergithub commented on src/modules/task.js
> +    `;
Creating the elements manipulating the DOM would make the code more readable. What do you think?
I'm not entirely sure if there is an agreement on how to approach creating the HTML element with JS or if it's about personal preference, but I found " writing HTML on the JS code a little messy. "

2022-05-02 21:11 UTC, wandergithub commented on src/modules/task-form.js
> +  constructor(form, isUpdating = false) {
What's the reason you didn't make this attributes part of the constructor?
If it's possible, I think it would be better practice.

2022-05-02 21:17 UTC, wandergithub requested changes
Nice Job Ronald
Summary:
✔️ Linters settled
✔️ Excellent documentation.
✔️ DRY: No functional repetition that could be automated.
✔️  YAGNI: Imported bootstrap and used it. 👍🏽  

Suggestions:
KISS: [Got this observations](https://github.com/rskinnerc/to-do-list-review/pull/1/files?short_path=b335630#r863189222) 
Best practices: [If it's possible, to improve readability](https://github.com/rskinnerc/to-do-list-review/pull/1/files?short_path=b335630#r863194191). Overall, nice use of classes.

2022-05-03 02:51 UTC, rskinnerc commented on src/modules/task.js
> +    `;
Thank you for your feedback. I'll have this in mind. I think when creating a small piece of HTML full of dynamic information, it is worth it creating like a template and use template literal. Creating elements 1-by-1 when its a lot of nodes/elements could create less readability, and make your code prone to errors. However, I will read and try to find more information about how to create HTML

2022-05-03 02:53 UTC, rskinnerc commented on src/modules/task-form.js
> +  constructor(form, isUpdating = false) {
Wander, thank you for your feedback. Even though it's not strictly necessary, by defining [public instance fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#public_instance_fields) you can ensure the field is always present and it makes the class definition a bit more self-documenting.

Please let me know any thoughts. Thank you :)

2022-05-03 13:41 UTC, merged